name: Release Build

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  build:
    name: "构建应用"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache: true
          cache-dependency-path: go.sum

      - name: Build
        run: |
          mkdir dist
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -trimpath -v -o dist/school_sdk_windows_amd64.exe .
          GOOS=windows GOARCH=386 go build -ldflags="-s -w" -trimpath -v -o dist/school_sdk_windows_386.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path:  dist/*

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files:  dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
